#!/bin/bash

OP_ENV_TO_SECRETS_CONFIG=(
    AWS_ACCESS_KEY_ID:AWS_TEXTRACT_USER:AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:AWS_TEXTRACT_USER:AWS_SECRET_ACCESS_KEY
)

if is_op_cli_available; then
    # >&2 echo "[DEBUG] 1Password CLI is installed and authenticated"
    for config_entry in "${OP_ENV_TO_SECRETS_CONFIG[@]}"; do
        eval "$(build_export_expression "$config_entry")"
    done
else
    >&2 echo "[ERROR] 1Password CLI is not installed or not authenticated"
fi
